controller:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  daemonset:
    useHostPort: true
  kind: DaemonSet
  service:
    externalTrafficPolicy: "Local"
    healthCheckNodePort: 0
    targetPorts:
      http: http
      https: https
    type: NodePort
    nodePorts:
      http: 32080
      https: 32443
defaultBackend:
  enabled: true